### ISSUE TITLE
I'm use mac, how to use System clang

### ISSUE THREAD

**Issue by wlanjie888** [oblitum/YouCompleteMe#9]
I'm use CPATH=/opt/local/include CC=/usr/bin/clang ./install.sh --clang-completer --system-libclang,
I'm have error 
Traceback (most recent call last):
  File "/Users/wlanjie/.vim/bundle/YouCompleteMe/third_party/ycmd/build.py", line 176, in <module>
    Main()
  File "/Users/wlanjie/.vim/bundle/YouCompleteMe/third_party/ycmd/build.py", line 171, in Main
    BuildYcmdLibs( GetCmakeArgs( args ) )
  File "/Users/wlanjie/.vim/bundle/YouCompleteMe/third_party/ycmd/build.py", line 149, in BuildYcmdLibs
    sh.make( '-j', NumCores(), build_target, _out = sys.stdout )
  File "/Users/wlanjie/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/sh/sh.py", line 1021, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/Users/wlanjie/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/sh/sh.py", line 486, in __init__
    self.wait()
  File "/Users/wlanjie/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/sh/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "/Users/wlanjie/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/sh/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_2: 

  RAN: '/usr/bin/make -j 8 ycm_support_libs'

  STDOUT:

  STDERR:
couldn't understand kern.osversion `14.1.0'
couldn't understand kern.osversion `14.1.0'
couldn't understand kern.osversion `14.1.0'
couldn't understand kern.osversion `14.1.0'
couldn't understand kern.osversion `14.1.0'
couldn't understand kern.osversion `14.1.0'
couldn't understand kern.osversion `14.1.0'
couldn't understand kern.osversion `14.1.0'
couldn't understand kern.osversion `14.1.0'
couldn't understand kern.osversion `14.1.0'
couldn't understand kern.osversion `14.1.0'
couldn't understand kern.osversion `14.1.0'
couldn't understand kern.osversion `14.1.0'
couldn't understand kern.osversion `14.1.0'
couldn't understand kern.osversion `14.1.0'
couldn't understand kern.osversion `14.1.0'
couldn't understand kern.osversion `14.1.0'
co... (26852 more, please see e.stderr)

**Comment by oblitum** [comment]
@wlanjie888 I'm unable to reproduce this error, it's quite different from issue #8, I have no idea what it means.

**Comment by oblitum** [comment]
@wlanjie888 is this the full output of the error? What comes before the traceback? Since ycmd has upgraded python for installation in 439a809a, traceback seem to have become useless.

**Comment by wlanjie888** [comment]
thank for your help,I want to know how to download Clang 3.7 revision 227309 (there's no Clang 3.7 release yet).

**Comment by oblitum** [comment]
@wlanjie888 you must build it from sources, please use google on how to do this.

**Comment by jsholmes** [comment]
You can also install using homebrew if you do --HEAD
